config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "tasks#index"

  resources :tasks do
    collection do
      post :tasks_employee_autocomplete
      post :autocomplete_search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.humanized_enum(enum, type)
    I18n.t(".tasks.#{enum}.#{type}")
  end
end

app/models/concerns/employee/search_filter.rb
module Employee::SearchFilter
  extend ActiveSupport::Concern

  included do
    scope :by_full_name, ->(q) {
      return current_scope if q.blank?

      where("CONCAT_WS(' ', first_name, last_name) ILIKE ?", "%#{q}%")
    }

    scope :by_email, ->(q) {
      return current_scope if q.blank?

      where("email ILIKE ?", "%#{q}%")
    }
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  include Employee::SearchFilter

  belongs_to :org
  has_many :tasks
end

app/models/org.rb
class Org < ApplicationRecord
  has_many :tasks
  has_many :employees

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :org
  belongs_to :employee

  enum :priority, { low: "low", medium: "medium", high: "high" }

  enum :status, { not_started: "not_started", in_progress: "in_progress", completed: "completed", blocked: "blocked" }

  def priority_label
    I18n.t("task.priorities.#{priority}", default: priority.humanize)
  end

  def status_label
    I18n.t("task.statuses.#{status}", default: status.humanize)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  LIMIT_PER_PAGE = 50.freeze

  include ActionView::RecordIdentifier

  before_action :set_tasks, only: %i[index destroy]
  before_action :set_task,  only: %i[update destroy]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: "You've successfully created the task."
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    @task_decorator = TaskDecorator.new(@task)

    render turbo_stream: [
      turbo_stream.replace(
        "show_task",
        partial: "tasks/show/task",
        locals: { task: @task }
      )
    ]
  end

  def edit
    @task = Task.find(params[:id])
    @task_decorator = TaskDecorator.new(@task)
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "You've successfully updated the task."
    else
      flash.now[:alert] = "Failed to update task, please select all options."
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "You've successfully deleted the task."
  end

  def tasks_employee_autocomplete
    render partial: "tasks/form/employee_search_box_results", locals: {
      employess: filtered_employees
    }
  end

  private

  MAX_QUANTITY_OF_RESULTS = 5
  def filtered_employees
    return if params[:search_box_query].blank?

    @filtered_employees = Org.last
                          .employees
                          .by_full_name(params[:search_box_query])
                          .by_email(params[:email])
                          .first(MAX_QUANTITY_OF_RESULTS)
  end

  def task_params
    if params[:task].is_a?(ActionController::Parameters)
      params.require(:task)
        .permit(
          :name, :description, :due_date, :priority, :status, :employee_id
        ).merge(org_id: Org.last.id)
    else
      {}
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def set_tasks
    @tasks = Task.all
      .paginate(page: page, per_page: LIMIT_PER_PAGE, total_entries: count)
  end

  def page
    [ params[:page].to_i, 1 ].max
  end

  def count
    Task.count
  end

  def handle_success_message
    message = "You've successfully updated the task."

    if params[:action] = "update"
      redirect_to tasks_path, notice: message
    else
      flash.now[:notice] = message
      render turbo_stream: [
        turbo_stream.replace(
          dom_id(@task),
          partial: "tasks/index/task",
          locals: { task: @task }
        ),
        turbo_stream.update("flash", partial: "layouts/flash")
      ]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def priority_color(status)
    {
      low:    :green,
      medium: :yellow,
      high:   :red
    }[status.downcase.to_sym] || :grey
  end

  def validation_error_for(task, field)
    if task.errors.has_key?(field)
      if field == :name || field == :description || field == :custom_category || field == :org_user_id
       content_tag(:div, task.errors[field].first, class: "error")
      else
       content_tag(:div, "Please select an option", class: "error")
      end
    end
  end

  def options_for_status(decorator)
    first_option = [ "Select a Status", "", { disabled: true, selected: true } ]

    [ first_option ] + decorator.status_options
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= render(AlertComponent.new(variant: flash_message_type(type), closable: true)) do %>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller] %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= turbo_frame_tag 'new_task' do %>
<% decorator = TaskDecorator.new(@task) %>
  <div class="task-form" data-controller="task" data-task-mode-value="<%= params[:action] %>" >
    <div class="form-wrapper">
      <%= render partial: 'tasks/form/assign_employee', locals: {
        employee: @task.employee,
      } %>
      <%= validation_error_for(@task, :org_user_id) %>
    </div>

    <div class="form-wrapper">
      <%= form_with model: task, class: 'form' do |form| %>
        <%= form.hidden_field :employee_id, value: @task.employee_id %>

        <fieldset>
            <div class="input-group">
              <div class="inline-inputs">
                <%= form.label :name, 'Task Title'  %>
                <%= form.text_field :name %>
                <%= validation_error_for(@task, :name) %>
              </div>

              <div class="inline-inputs">
                <%= form.label :description, 'Task Description' %>
                <%= form.text_area :description, {
                  rows: 5,
                  minlength: 3,
                  value: decorator&.description || @moment_decorator&.pre_filled_notes
                } %>
                <%# <%= validation_error_for(@task, :description) %>
              </div>

              <div class="inline-inputs">
                <%= form.label :due_date, t('.due_date') %>
                <%= form.date_field :due_date,
                  value: @task.due_date&.strftime('%Y-%m-%d') || @moment_decorator&.past_due_date&.strftime('%Y-%m-%d'),
                  min: Date.today.strftime('%Y-%m-%d')
                %>
                <%# <%= validation_error_for(@task, :due_date) %>
              </div>

              <div>
                <div class="inline-inputs">
                  <%= form.label :priority, t('.priority') %>
                  <%= form.select(:priority,
                      options_for_select([['Select Priority', '', {disabled: true, selected: true}]] + decorator.priority_options, @task.priority))
                  %>
                  <%# <%= validation_error_for(@task, :priority) %>
                </div>

                <div class="inline-inputs">
                  <%= form.label :status, t('.status') %>
                  <%= form.select :status,
                      options_for_select(
                        options_for_status(decorator),
                        @task.status
                      )
                  %>
                  <%# <%= validation_error_for(@task, :status) %>
                </div>
              </div>
            </div>
        </fieldset>

        <footer>
          <%= link_to 'Cancel', tasks_path, class: 'btn secondary' %>

          <%= render(ButtonComponent.new(data: { disable_with: 'Submitting' })) do %>
            <%= action_name == 'edit' ? 'Save' : 'Create' %>
          <% end %>
        </footer>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="dashboard">
  <div class="dashboard-sections">
   <%= render partial: 'form', locals: { task: @task } %>
  </div>
</div>

app/views/tasks/form/_assign_employee.html.erb
<fieldset>
    <div>
      <%= render(SearchBoxComponent.new(
        path: tasks_employee_autocomplete_tasks_path,
        domain: 'employees',
      )) do |search_box| %>
        <% search_box.with_input_component(
          label:  'Employee Name',
          placeholder: 'Type first 3 letters of employee name',
          value: employee&.first_name
        ) %>

        <% search_box.with_results do %>
          <%= render partial: 'tasks/form/employee_search_box_results' %>
        <% end %>
      <% end %>
    </div>
</fieldset>

app/views/tasks/form/_employee_search_box_results.html.erb
<% results = defined?(employess) ? employess : [] %>

<%= render(SearchBoxResultsComponent.new(turbo_frame_name: 'employees')) do |search_box_results| %>
  <% if results && results.any? %>
    <% results.each do |result| %>
      <%= search_box_results.with_option(
        trigger_attributes: {
          data: {
            action: 'click->task#handleSelectUser',
            'employee-id': result.id,
            'employee-name': result.first_name,
          }
        }
      ) do %>
        <%= result.first_name %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<% content_for(:global_stimilus_controller, 'task') %>

<div class="dashboard">
  <div class="dashboard-sections">
  <%= turbo_frame_tag 'new_task' do  %>
    <%= render partial: 'tasks/index/task_list', locals: {
      tasks: @tasks
    } %>

    <%= turbo_frame_tag 'show_task' %>


   
      <%= render(ButtonComponent.new(
        size: :l,
        href: new_task_path,
        icon: { name: 'add' },
        data: { turbo: true }
      )) do %>
          Add task
      <% end %>
   <% end %>
  </div>
</div>

app/views/tasks/index/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <% data = TaskDecorator.new(task) %>

  <li class="task" data-controller="task" data-task-translations-value="<%= I18n.t('tasks').to_json%>" data-action="click->task#showTask"  data-task-id="<%= task.id %>">
    <div>
      <div>
        <%= content_tag :div, class: ('empty-date' if data.due_date.blank?) do %>
          <%= render IconComponent.new(
            name: 'calendar-empty',
            source: 'microsoft-icons'
          ) %>

          <time><%= data.due_date_label %></time>
        <% end %>
      </div>

      <h3>
        <%= link_to task_path(data.id), data: { turbo_frame: dom_id(task) } do %>
          <%= data.name %>
        <% end %>
      </h3>


      <h3 style="color: green;"><%= data.description %></h3>
    </div>

    <div>
      <h1>status</h1>
      <%= render DropdownPopoverComponent.new do |component| %>
        <% component.with_trigger do %>
          <button>
            <%= render BadgeComponent.new(color: :grey, icon: 'chevron-down', icon_position: :trailing) do %>
              <%= data.status %>
            <% end %>
          </button>
        <% end %>

        <% Task.statuses.each do |_, status| %>
          <% component.with_item do %>
            <%= button_to I18n.t("task.statuses.#{status}", default: status.humanize), task_path(data.id),
              params: {
                task: {
                  id: data.id,
                  status: status
                },
                inline: true
              },
              method: :patch
            %>
          <% end %>
        <% end %>
      <% end %>


      <%= render DropdownPopoverComponent.new do |component| %>
        <% component.with_trigger do %>
          <button>
            <%= render BadgeComponent.new(color: priority_color(data.priority), icon: 'chevron-down', icon_position: :trailing) do %>
              <%= data.priority %>
            <% end %>
          </button>
        <% end %>

        <% Task.priorities.each do |_, priority| %>
          <% component.with_item do %>
            <%= button_to I18n.t("tasks.index.priorities.#{priority}"), task_path(data.id),  params: {
                task: {
                  id: data.id,
                  priority: priority
                },
                inline: true
              },
              method: :patch
            %>
          <% end %>
        <% end %>
      <% end %>

    </div>
    <div>
      <div>
        <%= render(AvatarComponent.new(
          size: 's',
          label: data.employee&.first_name
        )) %>
      </div>
      <%= render DropdownPopoverComponent.new do |component| %>
        <% component.with_trigger do %>
          <button>
            <%= render IconComponent.new(name: 'more', source: 'microsoft-icons') %>
          </button>
        <% end %>

        <% component.with_item do %>
          <%= link_to edit_task_path(data.id), data: { turbo: false } do %>
            Edit
          <% end %>
        <% end %>

        <% component.with_item do %>
            <%= link_to "Delete",
              task_path(task.id),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_frame: "_top" }
            %>
        <% end %>
      <% end %>
    </div>
  </li>
<% end %>

app/views/tasks/index/_task_list.html.erb
<%= turbo_frame_tag 'task_list' do %>
  <% if tasks.count == 0 %>
    <%= render EmptyComponent.new(
      title: t('.title'),
      subtitle: t('.subtitle'))
    %> 
  <% else %>
    <ul class="tasks">
      <% tasks.each do |task| %>
        <%= render partial: 'tasks/index/task', locals: { task: task } %>
      <% end %>

      <%= render(PaginationComponent.new(
        current_page: tasks.current_page,
        total_pages: tasks.total_pages
      )) %> 
    </ul>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<div class="dashboard">
  <div class="dashboard-sections">
   <%= render partial: 'form', locals: { task: @task } %>
  </div>
</div>

app/views/tasks/show/_task.html.erb
<%= turbo_frame_tag 'show_task' do %>
  <% data = TaskDecorator.new(task) %>

  <%= form_with model: task, url: edit_task_path(task), method: :get, data: { turbo: false } do |form| %>
    <%= render(DialogComponent.new(title: t('.title'), action_label: 'Edit', opened: false)) do |dialog| %>
      <ul class="task-information">
        <li>
          <h4><%= t('.name') %></h4>
          <p><%= data.name %></p>
        </li>

        <li>
          <h4><%= t('.description') %></h4>
          <p><%= data.description %></p>
        </li>

        <ul>
          <li>
            <span>
              <%= render IconComponent.new(name: 'calendar-empty', source: 'microsoft-icons') %>
              <%= data.due_date_label %>
            </span>
          </li>

          <li>
            <span>
              <%= render IconComponent.new(name: 'person', source: 'microsoft-icons') %>
              <%= data.employee&.first_name %>
            </span>
          </li>

          <li>
            <span>
              <%= render IconComponent.new(name: 'flag', source: 'microsoft-icons') %>
              <%= task.priority_label %>
            </span>
          </li>

          <li>
            <span>
              <%= render IconComponent.new(name: 'status', source: 'microsoft-icons') %>
              <%= task.status_label %>
            </span>
          </li>
        </ul>
      </ul>
    <% end %>
  <% end %>
<% end %>